services:
  postgres:
    image: postgres
    container_name: pibiti
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
volumes:
  postgres_data1: